### ISSUE TITLE
Missing sources of Icelandic text?

### ISSUE THREAD

**Issue by sveinbjornt** [mideind/Reynir#59]
The selection of websites scraped by Reynir seem rather arbitrary, with some notable sources of Icelandic news and text omitted, e.g. the following:

https://www.sedlabanki.is
http://dv.is
http://stundin.is (at least the open-access articles)
https://www.stjornarradid.is/raduneyti/utanrikisraduneytid/
http://hagstofa.is
http://althingi.is

**Comment by vthorsteinsson** [comment]
Yes, these are good points. There is already a primitive first version of a scraper for althingi.is in the repository (class AlthingiScraper in scrapers/default.py), but it is not active in the default real time scraping process. Adding scraping functionality for new websites is not difficult. Help would be appreciated!
